stages:
  - .pre
  - build
  - deploy
  - .post
  - test
  - security

include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Dependency-Scanning.gitlab-ci.yml
  - template: Security/DAST.gitlab-ci.yml
  - template: Security/Container-Scanning.gitlab-ci.yml
  - template: Security/IaC-Scanning.gitlab-ci.yml

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
  script:
    - echo "username  '$USERNAME'"
    - docker build -t "$USERNAME/getting-started:latest" .
    - echo "$PASSWORD" | docker login -u "$USERNAME" --password-stdin
    - docker push "$USERNAME/getting-started:latest"

deploy:
  stage: deploy
  script:
    - echo "Deploy step (you can configure this later)"



