stages:
  - build
  - deploy

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t $DOCKER_USERNAME/getting-started:latest .
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker push "$DOCKER_USERNAME"/getting-started:latest

deploy:
  stage: deploy
  script:
    - echo "Deploy step (you can configure this later)"

